export const LOAD_SEARCH_MOVIE = 'LOAD_SEARCH_MOVIE';
export const LOAD_SEARCH_MOVIE_SUCCESS = 'LOAD_SEARCH_MOVIE_SUCCESS';
export const LOAD_SEARCH_MOVIE_FAIL = 'LOAD_SEARCH_MOVIE_FAIL';

export const RESET_SEARCH_MOVIE = 'RESET_SEARCH_MOVIE';